const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

export {
  ALERT, NEW_MESSAGE, NEW_MESSAGE_ALERT,
  NEW_REQUEST, REFETCH_CHATS, START_TYPING,
  STOP_TYPING
};
